# Generated by Django 5.2.9 on 2025-12-05 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(blank=True, max_length=250, null=True, verbose_name="Место")),
                ("time", models.DateTimeField(verbose_name="Время в формате YYYY-MM-DD HH:MM[:ss]")),
                ("action", models.CharField(max_length=500, verbose_name="Действие")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                ("periodicity", models.PositiveSmallIntegerField(verbose_name="Периодичность")),
                ("award", models.CharField(blank=True, max_length=500, null=True, verbose_name="Вознаграждение")),
                ("duration", models.DurationField(verbose_name="Время на выполнение")),
                ("public_flag", models.BooleanField(default=False, verbose_name="Признак публичности")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
