# Generated by Django 5.2.9 on 2025-12-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(verbose_name="Время в формате YYYY-MM-DD HH:MM[:ss]"),
        ),
    ]
