# Generated by Django 5.2.9 on 2025-12-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Периодичность"),
        ),
    ]
