# Generated by Django 5.2.9 on 2025-12-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name="Периодичность"),
        ),
    ]
