# Generated by Django 5.2.9 on 2025-12-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(verbose_name="Признак приятной привычки"),
        ),
    ]
