# Generated by Django 5.2.9 on 2025-12-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_is_pleasant"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_execution_time",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Дата и время последнего выполнения"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="next_execution_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время следующего выполнения"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(verbose_name="Время в формате HH:MM[:ss]"),
        ),
    ]
