# Generated by Django 5.2.9 on 2025-12-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_habit_last_execution_time_habit_next_execution_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="last_execution_time",
            new_name="last_execution_datetime",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="next_execution_time",
            new_name="next_execution_datetime",
        ),
    ]
