# Generated by Django 5.2.9 on 2025-12-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0008_rename_last_execution_time_habit_last_execution_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(blank=True, null=True, verbose_name="Время на выполнение"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="Время в формате HH:MM[:ss]"),
        ),
    ]
